name: Utkarsh Automation

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify Java version
          distribution: 'temurin'  # Choose the JDK distribution

     # Step 3: Navigate to the correct directory (if `pom.xml` is not in the root)
      - name: Build with Maven
        run: |
          cd <path-to-project-root> # Replace with the relative path to the directory containing `pom.xml`
          mvn clean install

      # Step 5: Run tests
      - name: Run tests
        run: mvn test
