name: Utkarsh Web Automation

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the Java version
          distribution: 'temurin'  # Use the Temurin JDK distribution

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Path to Maven's dependency repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Ensure we are in the correct directory
      - name: Change directory to the root project
        run: cd ${{ github.workspace }}  # This ensures we are in the root directory

      # Step 5: Build the project
      - name: Build with Maven
        run: mvn clean install

      # Step 6: Run tests
      - name: Run tests
        run: mvn test

  deploy:
    needs: build  # Deploy only after the build job is successful
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Deploy artifacts (optional)
      - name: Deploy artifacts
        run: |
          echo "Deploying the application..."
          # Add your deployment script here (e.g., upload to a server, publish to a registry)
